### ISSUE TITLE
Not usable with babylon parser's custom nodes

### ISSUE THREAD

**Issue by suchipi** [facebook/jscodeshift#149]
Because Babylon's output format [differs from ESTree](https://github.com/babel/babylon#output), when using babylon as the parser, there are cases where unfamiliarity with nodes not present in `ast-types` causes an error to be thrown:

<details>
<summary>

jscodeshift output</summary>

```
$ jscodeshift ./src --parser babylon

Processing 1 files... 
Spawning 1 workers...
Sending 1 files to free worker...
 ERR src/target.js Transformation error
Error: did not recognize object of type "ObjectProperty"
    at Object.getFieldNames (/home/suchipi/Code/jscodeshift-babylon-issue-repro/node_modules/recast/node_modules/ast-types/lib/types.js:663:19)
    at getSortedChildNodes (/home/suchipi/Code/jscodeshift-babylon-issue-repro/node_modules/recast/lib/comments.js:50:23)
    at getSortedChildNodes (/home/suchipi/Code/jscodeshift-babylon-issue-repro/node_modules/recast/lib/comments.js:63:9)
    at getSortedChildNodes (/home/suchipi/Code/jscodeshift-babylon-issue-repro/node_modules/recast/lib/comments.js:63:9)
    at decorateComment (/home/suchipi/Code/jscodeshift-babylon-issue-repro/node_modules/recast/lib/comments.js:73:22)
    at decorateComment (/home/suchipi/Code/jscodeshift-babylon-issue-repro/node_modules/recast/lib/comments.js:84:13)
    at decorateComment (/home/suchipi/Code/jscodeshift-babylon-issue-repro/node_modules/recast/lib/comments.js:84:13)
    at decorateComment (/home/suchipi/Code/jscodeshift-babylon-issue-repro/node_modules/recast/lib/comments.js:84:13)
    at /home/suchipi/Code/jscodeshift-babylon-issue-repro/node_modules/recast/lib/comments.js:129:9
    at Array.forEach (native)
All done. 
Results: 
1 errors
0 unmodified
0 skipped
0 ok
Time elapsed: 1.178seconds 
```

</details>

I have created a repro case at [suchipi/jscodeshift-babylon-issue-repro](https://github.com/suchipi/jscodeshift-babylon-issue-repro).
To test, clone the repo, run `npm install`, then run `npm start`.
### Expected Behavior

jscodeshift either (in order of desirability):
- uses babel-types instead of ast-types when `babylon` is the selected parser
- lets the user provide their own visitor keys, builders, etc to use
- completely ignores nodes whose types are unique to the [Babel AST Format](https://github.com/babel/babylon/blob/master/ast/spec.md)
- does not support babylon as a parser by default
### Current Behavior

An error is thrown when encountering a node type not present in `ast-types`.

---

I recognize that the `ast-types` dependency is within `recast`, so addressing this issue may require a change there.

**Comment by fkling** [comment]
Yep, that's a known problem. Usually ast-types needs to be updated. Maybe we could provide our own type definitions for babylon, but recast still wouldn't be able to print them (so we would need a way to extend recast's printer).

Of course completely switching flow is an option too.

**Comment by hzoo** [comment]
I have 2 unfinished PRs for recasts printer and for ast-types if anyone can help with that

**Comment by benjamn** [comment]
What kind of help do you need?

**Comment by hzoo** [comment]
https://github.com/benjamn/ast-types/pull/162 I think I just need to fix tests - haven't looked at it in a while

**Comment by hzoo** [comment]
landed ^ so ast-types/recast is supported now (might have some bugs)

**Comment by suchipi** [comment]
My apologies; I deleted the repro repo from github because I thought it was in another issue (which has been closed), not in this one which is still open.

I should still have it on my box; I'll test it and report back.

**Comment by fkling** [comment]
I guess it's fine to close this for now. If this comes

**Comment by suchipi** [comment]
Sorry I never got back on this. I still haven't tested it but with @hzoo's updates it should work
