### ISSUE TITLE
Unexpected token on a working flow code

### ISSUE THREAD

**Issue by alanzanattadev** [facebook/jscodeshift#177]
Hi,

I have an error on the returned object type annotation
`(state: any, ownProps: any): {caregivers: Array<Caregiver>, patients: Array<Patient>, appointments: Array<Appointment>} => ({`

`
SyntaxError: Unexpected token (283:122)
      
      at Parser.Object.<anonymous>.pp.raise (node_modules/babel-core/node_modules/babylon/lib/parser/location.js:24:13)
      at Parser.Object.<anonymous>.pp.unexpected (node_modules/babel-core/node_modules/babylon/lib/parser/util.js:82:8)
      at Parser.Object.<anonymous>.pp.expect (node_modules/babel-core/node_modules/babylon/lib/parser/util.js:76:33)
      at Parser.Object.<anonymous>.pp.parseExprList (node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:785:12)
      at Parser.Object.<anonymous>.pp.parseSubscripts (node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:270:29)
      at Parser.Object.<anonymous>.pp.parseExprSubscripts (node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:240:17)
      at Parser.Object.<anonymous>.pp.parseMaybeUnary (node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:217:19)
      at Parser.Object.<anonymous>.pp.parseExprOps (node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:163:19)
      at Parser.Object.<anonymous>.pp.parseMaybeConditional (node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:145:19)
      at Parser.Object.<anonymous>.pp.parseMaybeAssign (node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:112:19)
      at Parser.Object.<anonymous>.pp.parseExport (node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:682:21)
      at Parser.parseExport (node_modules/babel-core/node_modules/babylon/lib/plugins/flow.js:713:20)
      at Parser.Object.<anonymous>.pp.parseStatement (node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:115:90)
      at Parser.parseStatement (node_modules/babel-core/node_modules/babylon/lib/plugins/flow.js:655:22)
      at Parser.Object.<anonymous>.pp.parseTopLevel (node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:30:21)
      at Parser.parse (node_modules/babel-core/node_modules/babylon/lib/parser/index.js:70:17)
      at Object.parse (node_modules/babel-core/node_modules/babylon/lib/index.js:45:50)
      at Object.parse (node_modules/babel-core/lib/api/node.js:160:21)
      at Object.parse (node_modules/recast/lib/parser.js:26:34)
      at fromSource (node_modules/jscodeshift/dist/core.js:84:25)
      at core (node_modules/jscodeshift/dist/core.js:46:5)
      at transformer (move-file.js:24:10)
      at runTest (node_modules/jscodeshift/dist/testUtils.js:60:18)
      at Object.it (node_modules/jscodeshift/dist/testUtils.js:82:7)
`

`export default connect(
  (state: any, ownProps: any): {caregivers: Array<Caregiver>, patients: Array<Patient>, appointments: Array<Appointment>} => ({
    caregivers: state.data.get('caregivers', List()).toJS(),
    patients: state.data.get('patients', List()).toJS(),
    appointments: state.data.get('appointments', List()).toJS(),
  }),
  (dispatch, ownProps) => ({
    dispatch,
    onSave: (infos, appointmentId) => dispatch(
      appointmentId ?
      actions.updateByID(convertStateToAppointment(infos, parseInt(appointmentId), ownProps), appointmentId)
      :
      actions.create(convertStateToAppointment(infos, undefined, ownProps))
    )
  })
)(AppointmentCreation);`

It's supposed to be working as in webpack or raw babel.

Thank you ! :)

**Comment by fkling** [comment]
Did you have a look at #172 ?

**Comment by alanzanattadev** [comment]
Hmmm, seems to have fixed the problem, thank you ;) But can jscodeshift change its default parser to something more ES2017 friendly ?
