### ISSUE TITLE
getting errors on files with decorators

### ISSUE THREAD

**Issue by farhansalam** [facebook/jscodeshift#232]
We are using `@Radium` decorators in our jsx file and running `react-codemods` which is giving 

```
 ERR [ *path* ] Transformation error
SyntaxError: Unexpected token (16:0)
    at Parser.pp$5.raise (/Users/farhan/.config/yarn/global/node_modules/jscodeshift/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/Users/farhan/.config/yarn/global/node_modules/jscodeshift/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp$1.parseDecorator (/Users/farhan/.config/yarn/global/node_modules/jscodeshift/node_modules/babylon/lib/index.js:1939:10)
    at Parser.pp$1.parseDecorators (/Users/farhan/.config/yarn/global/node_modules/jscodeshift/node_modules/babylon/lib/index.js:1924:26)
    at Parser.pp$1.parseStatement (/Users/farhan/.config/yarn/global/node_modules/jscodeshift/node_modules/babylon/lib/index.js:1818:10)
    at Parser.pp$1.parseBlockBody (/Users/farhan/.config/yarn/global/node_modules/jscodeshift/node_modules/babylon/lib/index.js:2268:21)
    at Parser.parseBlockBody (/Users/farhan/.config/yarn/global/node_modules/jscodeshift/node_modules/babylon/lib/index.js:4820:18)
    at Parser.pp$1.parseTopLevel (/Users/farhan/.config/yarn/global/node_modules/jscodeshift/node_modules/babylon/lib/index.js:1778:8)
    at Parser.parse (/Users/farhan/.config/yarn/global/node_modules/jscodeshift/node_modules/babylon/lib/index.js:1673:17)
    at Object.parse (/Users/farhan/.config/yarn/global/node_modules/jscodeshift/node_modules/babylon/lib/index.js:7305:37)

```

How to use babel plugins like `transform-decorators-legacy` with jscodeshift.

**Comment by DrewML** [comment]
You'll need to specify `Babylon` as the parser (documentation in the readme).

`jscodeshift` [already enables the `decorators` parser flag in `Babylon`](https://github.com/facebook/jscodeshift/blob/e469635b8fe050f84ad042c7fa5189d75f49d88d/parser/babylon.js#L27), which is [the plugin](https://unpkg.com/babel-plugin-syntax-decorators@6.13.0/lib/index.js) that [decorators-legacy uses](https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy/blob/5feb2c24eb9d06fc965a2fa12c9114a0779b9299/src/index.js#L271)

**Comment by farhansalam** [comment]
@DrewML Works perfectly with `babylon` i was trying with babel.
