### ISSUE TITLE
This experimental syntax requires enabling one of the following parser plugin(s) with Babel

### ISSUE THREAD

**Issue by GCorbel** [facebook/jscodeshift#256]
I'm working on a ember app where I use decorators. I want to use [es5-getter-ember-codemod](https://rawgit.com/rondale-sc/es5-getter-ember-codemod/master/es5-getter-ember-codemod.js) so I did : 

```
jscodeshift -t https://rawgit.com/rondale-sc/es5-getter-ember-codemod/master/es5-getter-em
ber-codemod.js --babel --parser babel ./app/ 
ERR app/models/user.js Transformation error
SyntaxError: This experimental syntax requires enabling one of the following parser plugin(s): 'decorators, decorators2' (5:2)
    at _class.raise (/home/dougui/.config/yarn/global/node_modules/jscodeshift/node_modules/babylon/lib/index.js:779:15)
    at _class.expectOnePlugin (/home/dougui/.config/yarn/global/node_modules/jscodeshift/node_modules/babylon/lib/index.js:2101:18)
    at _class.parseDecorator (/home/dougui/.config/yarn/global/node_modules/jscodeshift/node_modules/babylon/lib/index.js:4126:10)
    at _class.parseObj (/home/dougui/.config/yarn/global/node_modules/jscodeshift/node_modules/babylon/lib/index.js:3475:34)
    at _class.parseExprAtom (/home/dougui/.config/yarn/global/node_modules/jscodeshift/node_modules/babylon/lib/index.js:3124:21)
    at _class.parseExprAtom (/home/dougui/.config/yarn/global/node_modules/jscodeshift/node_modules/babylon/lib/index.js:5480:54)
    at _class.parseExprAtom (/home/dougui/.config/yarn/global/node_modules/jscodeshift/node_modules/babylon/lib/index.js:8119:52)
    at _class.parseExprSubscripts (/home/dougui/.config/yarn/global/node_modules/jscodeshift/node_modules/babylon/lib/index.js:2758:21)
    at _class.parseMaybeUnary (/home/dougui/.config/yarn/global/node_modules/jscodeshift/node_modules/babylon/lib/index.js:2737:21)
    at _class.parseExprOps (/home/dougui/.config/yarn/global/node_modules/jscodeshift/node_modules/babylon/lib/index.js:2646:21)
All done. 
Results: 
10 errors
10 unmodified
0 skipped
0 ok
```

With `--parse babylon` I have no errors but nothing is modified.

I tried to add a `.babelrc` file with : 

```
{
  "plugins": ["transform-decorators-legacy"],
}
```

But it doesn't worked.

It works when I use `babel ./app`.

This can be related to #252 

Do you have a clue?

**Comment by fkling** [comment]
What if you use `--parser babylon` instead?

**Comment by GCorbel** [comment]
I say it in the message :wink: 

> With --parse babylon I have no errors but nothing is modified.

**Comment by fkling** [comment]
Woops, sorry 😟

**Comment by optikalefx** [comment]
+1, same issue

**Comment by sijad** [comment]
same here

**Comment by agon21** [comment]
+1

**Comment by xliu2401** [comment]
+1

**Comment by luyi985** [comment]
+1

**Comment by jbadan** [comment]
Seems like this is caused by #245  -  `babelrc` is hardcoded to false.

**Comment by anaibol** [comment]
+1

**Comment by jbadan** [comment]
I ended up doing the same as @loopmode above, but got it working by tweaking some different settings in that block.

I eventually just switched to using `--parser flow` to avoid the problem entirely.

**Comment by loopmode** [comment]
Uh, I didn't even try `--parser flow` - if it works, that's awesome. Will check.

**Comment by jbadan** [comment]
@loopmode I just remembered how I got adding `require('babel-plugin-transform-decorators-legacy')` to the plugins array working - the docs say that `babel: true` is the default (separate from the `--parser` flag), but it doesn't actually come through if you log out that block of text. If you hardcode `babel:true`, you'll actually hit that block and it will work :)

**Comment by jacobq** [comment]
FWIW, when I tried running with `--parser flow` the error message about needing a plugin for decorator support went away, however, the transformation did not change any of the `@service i18n` lines. Also, it didn't seem to change any of the lines like `this.owner.lookup('service:i18n')` or `import tHelper from 'ember-i18n/helper';` (e.g. as used in many test files).

**Comment by AndersDJohnson** [comment]
FYI @fkling Your code example there has `--parse-config` rather than `--parser-config`.

**Comment by jbmilgrom** [comment]
Does the parser configuration work? The plugins included in my custom babel config referenced by the `--parser-config` flag appear to be ignored, resulting in parse errors. Think I'm seeing others with same issue https://github.com/expo/expo-cli/issues/676#issuecomment-505793327

**Comment by jbmilgrom** [comment]
Ok so the way I got this to work was to follow the internal syntax of babylon [defaultOptions](https://github.com/facebook/jscodeshift/blob/master/parser/babylon.js#L13). I copied over the default options to an `.babelrc-codemod.json` file and changed `['decorators', {decoratorsBeforeExport: false}]` to `decorators-legacy`. Now when running

`yarn jscodeshift --parser=babylon --parser-config ./.babelrc-codemod.json  src/some/file/with/legacy/decorators.js` 

Can parse with no errors. Does babylon require different syntax than babel? custom configuration handling unique to jscodeshift? Not sure why this works

**Comment by ralstonJ** [comment]
@fkling Can we have the json file configs for this solution.
