### ISSUE TITLE
Jscodeshift class.js transformation givign jscodeshift TypeError: Cannot read property 'process' of undefined error

### ISSUE THREAD

**Issue by tulasimcabca** [facebook/jscodeshift#299]
C:\Users\xxxx\Desktop\Migration\react-codemod-master\transforms>jscodeshift -t class.js test.js
Processing 1 files...
Spawning 1 workers...
Sending 1 files to free worker...
C:\Users\xxx\AppData\Roaming\npm\node_modules\jscodeshift\node_modules\flow-parser\flow_parser.js:2
(function(i4){"use strict";var uD=254,qu=43595,gF=42237,bM=43123,C4="??",u$="children",C3="Identifier",jD=16777215,io=43347,gE=126467,kF=12287,kG="variance",hZ=12335,bL=65370,Cx=">>>",Cy="pattern",kI=8202,eU=65007,bJ=119969,bK=43071,q6=115,D9="!",D_="directive",mp="consequent",lS=512,dj=64279,di=8485,dh=66204,eT=120539,dg=64297,kZ="params",ix="@[<2>[",iM=128,df=8488,hY=68102,C2=235,bI=42999,qa=-43,de=12589,ns="constructor",bH=126503,ln="yield",qt=68096,Cv=-53,Cw="fd ",dd=120744,eS=126560,u_="start",ug="target",C1="_method",eR=177972,hX=44015,p$="var",dc=65855,Dr="impltype",gD=43776,ni="0o",ht=43215,db=12592,qs=">",gC=12336,da=42124,bG=120512,uC="decorators",gB=8489,eQ=66334,bF=68115,C0="update",eP=64324,gA=67592,bE=126529,iH="%B",bD=43784,c_=119807,c$=8304,gz=120137,qr=69807,nn="method",p_=69926,u9="throw",bC=65595,gw=126578,gx=64322,gy=11735,Cu="of",Ct=">>",eO=178205,eN=8487,Dq="Popping lex mode from empt

TypeError: Cannot read property 'process' of undefined
    at process (C:\Users\xxx\AppData\Roaming\npm\node_modules\jscodeshift\node_modules\flow-parser/flow_parser.js:293:70)
    at Object.<anonymous> (C:\Users\xxx\AppData\Roaming\npm\node_modules\jscodeshift\node_modules\flow-parser/flow_parser.js:2:2)
    at Module._compile (module.js:652:30)
    at Module._compile (C:\Users\xxx\AppData\Roaming\npm\node_modules\jscodeshift\node_modules\pirates\lib\index.js:83:24)
    at Module._extensions..js (module.js:663:10)
    at Object.newLoader [as .js] (C:\Users\xxx\AppData\Roaming\npm\node_modules\jscodeshift\node_modules\pirates\lib\index.js:88:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
All done.
Results:
0 errors
0 unmodified
0 skipped
0 ok
Time elapsed: 2.160seconds

**Comment by fkling** [comment]
Can you provide the output of `jscodeshift --version` ?

**Comment by Ranguro** [comment]
I'm facing the same issue when running:

 `jscodeshift -t ./react-codemod/transforms/class.js --mixin-module-name=react-addons-pure-render-mixin --flow=true --pure-component=true --remove-runtime-proptypes=false /path/to/your/repo `

![image](https://user-images.githubusercontent.com/4252088/51549918-e32ab080-1e30-11e9-9189-8af9607a111c.png)

My jscodeshift version is 0.6.2

**Comment by tulasimcabca** [comment]
Hello , the issue is with babel . Please add —no-babel option with the above command and see it that solves the problem.
