### ISSUE TITLE
Jest tests fails for reverse-identifiers

### ISSUE THREAD

**Issue by pashaie** [facebook/jscodeshift#353]
I'm not sure if this is a jest issue or jscodeshift (probably jest). But would appreciate any feedback.
I used `reverse-identifiers.js` in jscodeshift sample project and only adjusted `defineTest` require path like below:
```
const defineTest = require('jscodeshift/dist/testUtils').defineTest;
const defineInlineTest = require('jscodeshift/dist/testUtils').defineInlineTest;
```

running jest, results in baffling errors:
```
 FAIL  sample/__tests__/reverse-identifiers-test.js
  reverse-identifiers
    × transforms correctly (494ms)
    × transforms correctly using "typescript/reverse-identifiers" data (3ms)
    × Test (7ms)
    √ Reverses function names (7ms)

  ● reverse-identifiers › transforms correctly

    expect(received).toEqual(expected) // deep equality

    - Expected
    + Received

    - var droWtsrif = 'Hello ';
    + var droWtsrif = 'Hello ';
    - var droWdnoces = 'world';
    + var droWdnoces = 'world';
      var egassem = droWtsrif + droWdnoces;

      at runInlineTest (node_modules/jscodeshift/dist/testUtils.js:36:33)
      at runTest (node_modules/jscodeshift/dist/testUtils.js:73:3)
      at Object.it (node_modules/jscodeshift/dist/testUtils.js:90:7)

  ● reverse-identifiers › transforms correctly using "typescript/reverse-identifiers" data

    ENOENT: no such file or directory, open 'C:\ws\js2ts\unit\sample\__testfixtures__\typescript\reverse-identifiers.input.js'

      at runTest (node_modules/jscodeshift/dist/testUtils.js:66:21)
      at Object.it (node_modules/jscodeshift/dist/testUtils.js:90:7)

  ● reverse-identifiers › Test

    expect(received).toEqual(expected) // deep equality

    - Expected
    + Received

    - var droWtsrif = 'Hello ';
    + var droWtsrif = 'Hello ';
    - var droWdnoces = 'world';
    + var droWdnoces = 'world';
      var egassem = droWtsrif + droWdnoces;

      at runInlineTest (node_modules/jscodeshift/dist/testUtils.js:36:33)
      at Object.it (node_modules/jscodeshift/dist/testUtils.js:98:5)

Test Suites: 1 failed, 1 total
Tests:       3 failed, 1 passed, 4 total
Snapshots:   0 total
Time:        5.186s
Ran all test suites.

```

**Comment by gkz** [comment]
Let us know if this is still an issue

**Comment by pashaie** [comment]
I haven't checked that project for many years,
Probably it's fixed in newest version.

Thanks
