### ISSUE TITLE
closestScope is not a method when running via node. Works using defineTest

### ISSUE THREAD

**Issue by jamime** [facebook/jscodeshift#362]
I have a simple transformation that creates a new collection as part of it.
```js
function transformer(fileInfo, api, options) {
  const j = api.jscodeshift;
  const root = j(fileInfo.source);

  const buttons = root
    .find(j.ImportDeclaration, {
      source: { value: "my-lib/components/button" }
    })
    .find(j.ImportDefaultSpecifier)
    .map(path => {
      const id = path.node.local.name;
      if (id) {
        return Collection.fromPaths([path])
          .closestScope() // This method is unavailable when running via node but available when running jest
          .findJSXElements(id)
          .paths();
      }
    });
// ...
}
```
When I run my tests everything works fine.

```
npm test

> carbon-codemod@1.0.0 test /Users/jamime/codemod
> jest

 PASS  button/__tests__/button-destructive-test.js
  button-destructive
    ✓ transforms correctly using "RegularImport" data (102ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        0.702s, estimated 1s
Ran all test suites.
```

However, when I actually try to run the codemod it fails with 
```sh
node  ./node_modules/.bin/jscodeshift -t ./button/button-destructive.js ./button/__testfixtures__/RegularImport.input.js
Processing 1 files... 
Spawning 1 workers...
Sending 1 files to free worker...
 ERR ./button/__testfixtures__/RegularImport.input.js Transformation error (Collection.fromPaths(...).closestScope is not a function)
TypeError: Collection.fromPaths(...).closestScope is not a function
    at NodePath.root.find.find.map.path (/Users/jamime/codemod/button/button-destructive.js:18:12)
    at NodePath.<anonymous> (/Users/jamime/codemod/node_modules/jscodeshift/src/Collection.js:121:29)
    at __paths.forEach (/Users/jamime/codemod/node_modules/jscodeshift/src/Collection.js:75:36)
    at Array.forEach (<anonymous>)
    at Collection.forEach (/Users/jamime/codemod/node_modules/jscodeshift/src/Collection.js:74:18)
    at Collection.map (/Users/jamime/codemod/node_modules/jscodeshift/src/Collection.js:119:10)
    at transformer (/Users/jamime/codemod/button/button-destructive.js:14:6)
All done. 
Results: 
1 errors
0 unmodified
0 skipped
0 ok
Time elapsed: 0.640seconds 
```

I've pushed this example to GitHub [here](https://github.com/jamime/jscodeshift-bug), I would appreciate any guidance.

**Comment by jamime** [comment]
Closing. 

I'm not sure of the exact reason why it passes in jest but not in node. Possibly something to do with the worker having a different copy of `Collection`. However, changing 
```js
Collection.fromPaths([path])
```
to
```js
j([path])
```
fixed my issue, simply using the instance that already has the `Node` methods registered.
