### ISSUE TITLE
jscodeshift throws an error when trying to transfrom modules

### ISSUE THREAD

**Issue by alolonghun** [facebook/jscodeshift#376]
I installed jscodeshift globally and ran the command `jscodeshift -t index.js test.js` according to the guidance of the document. However, I will eventually encounter the following problems：
```js
Processing 1 files... 
Spawning 1 workers...
Sending 1 files to free worker...
/usr/local/lib/node_modules/jscodeshift/src/Worker.js:24
} catch {}
        ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
All done. 
Results: 
0 errors
0 unmodified
0 skipped
0 ok
Time elapsed: 0.071seconds
```
Finally, I found the error was due to the catch module syntax of line 24 in `/src/work.js`, which caused the error, please fix it as soon as possible!

**version**：jscodeshift@0.9.0

**Comment by samwgoldman** [comment]
Fixed in 48355d9935060ea725689108ec96d6bd44bee8ee. Thanks for the report!
