### ISSUE TITLE
did not recognize object of type "PropertyDefinition"

### ISSUE THREAD

**Issue by changjianhong** [facebook/jscodeshift#450]
error stack:
  Error: did not recognize object of type "PropertyDefinition"
    at Object.getFieldNames (/Users/changjianhong/Desktop/rn-codemod/node_modules/ast-types/lib/types.js:660:19)
    at visitChildren (/Users/changjianhong/Desktop/rn-codemod/node_modules/ast-types/lib/path-visitor.js:184:36)
    at Visitor.PVp.visitWithoutReset (/Users/changjianhong/Desktop/rn-codemod/node_modules/ast-types/lib/path-visitor.js:166:20)
    at NodePath.each (/Users/changjianhong/Desktop/rn-codemod/node_modules/ast-types/lib/path.js:87:26)
    at visitChildren (/Users/changjianhong/Desktop/rn-codemod/node_modules/ast-types/lib/path-visitor.js:178:18)
    at Visitor.PVp.visitWithoutReset (/Users/changjianhong/Desktop/rn-codemod/node_modules/ast-types/lib/path-visitor.js:166:20)
    at visitChildren (/Users/changjianhong/Desktop/rn-codemod/node_modules/ast-types/lib/path-visitor.js:203:25)
    at Visitor.PVp.visitWithoutReset (/Users/changjianhong/Desktop/rn-codemod/node_modules/ast-types/lib/path-visitor.js:166:20)
    at visitChildren (/Users/changjianhong/Desktop/rn-codemod/node_modules/ast-types/lib/path-visitor.js:203:25)
    at Visitor.PVp.visitWithoutReset (/Users/changjianhong/Desktop/rn-codemod/node_modules/ast-types/lib/path-visitor.js:166:20)
 ERR /Users/changjianhong/58/rn/react-native-apps/packages/live/containers/LiveList/index.js Transformation error (did not recognize object of type "PropertyDefinition")
Error: did not recognize object of type "PropertyDefinition"
    at Object.getFieldNames (/Users/changjianhong/Desktop/rn-codemod/node_modules/ast-types/lib/types.js:660:19)
    at getSortedChildNodes (/Users/changjianhong/Desktop/rn-codemod/node_modules/recast/lib/comments.js:53:23)
    at getSortedChildNodes (/Users/changjianhong/Desktop/rn-codemod/node_modules/recast/lib/comments.js:62:9)
    at getSortedChildNodes (/Users/changjianhong/Desktop/rn-codemod/node_modules/recast/lib/comments.js:62:9)
    at decorateComment (/Users/changjianhong/Desktop/rn-codemod/node_modules/recast/lib/comments.js:70:22)
    at decorateComment (/Users/changjianhong/Desktop/rn-codemod/node_modules/recast/lib/comments.js:82:13)
    at decorateComment (/Users/changjianhong/Desktop/rn-codemod/node_modules/recast/lib/comments.js:82:13)
    at /Users/changjianhong/Desktop/rn-codemod/node_modules/recast/lib/comments.js:119:9
    at Array.forEach (<anonymous>)
    at Object.attach (/Users/changjianhong/Desktop/rn-codemod/node_modules/recast/lib/comments.js:117:14)
All done. 
  
  
  "dependencies": {
    "commander": "^6.2.1",
    "execa": "^5.0.0",
    "glob": "^7.1.7",
    "jscodeshift": "^0.11.0",
    "lodash": "^4.17.20",
    "prettier": "^2.2.1",
    "readdir": "^1.0.2"
  }

**Comment by changjianhong** [comment]
flow-parser(0.152.0 -> 0.159.0) cause to The class properties cannot be recognized

**Comment by osiux** [comment]
@changjianhong were you able to fix this? how?

**Comment by jennykortina** [comment]
i am having this error as well.  Does anyone know how to fix this?

**Comment by alexander-schranz** [comment]
I did run into this error message when trying out: https://github.com/Khan/flow-to-ts

I thought I was clever and did just:

```js
npx flow-to-js ..
```

Then found out that `flow-to-js` is another library then `@khanacademy/flow-to-ts`:
So correct way is then:

```
yarn global add @khanacademy/flow-to-ts
flow-to-js ./**/.js
```

Just let this here if it maybe helps somebody which googles the same error message as me and is landing here.
