### ISSUE TITLE
Error: Cannot find module 'lodash'

### ISSUE THREAD

**Issue by JuanSeBestia** [facebook/jscodeshift#451]
Usually I use this tools to migrate some components to TypeScript, but today it show me an error

```bash
npx jscodeshift -t https://raw.githubusercontent.com/mskelton/prop-types-to-ts/master/transform.ts src/auth/ForgotPasswordPage.jsx
Processing 1 files... 
Spawning 1 workers...
Sending 1 files to free worker...
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'lodash'
Require stack:
- /usr/local/lib/node_modules/jscodeshift/parser/tsx.js
- /usr/local/lib/node_modules/jscodeshift/src/getParser.js
- /usr/local/lib/node_modules/jscodeshift/src/Worker.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/jscodeshift/parser/tsx.js:11:11)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module._compile (/usr/local/lib/node_modules/jscodeshift/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.newLoader [as .js] (/usr/local/lib/node_modules/jscodeshift/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/jscodeshift/parser/tsx.js',
    '/usr/local/lib/node_modules/jscodeshift/src/getParser.js',
    '/usr/local/lib/node_modules/jscodeshift/src/Worker.js'
  ]
}
All done. 
Results: 
0 errors
0 unmodified
0 skipped
0 ok
Time elapsed: 1.202seconds 
```
I tried installed in the current project

```bash
npm i lodash --save
```
and also install it globally

```bash
npm i -g lodash
```

**Comment by Daniel15** [comment]
Are you on an old version maybe? It looks like the lodash requirement was removed in #432.
