### ISSUE TITLE
Transformation error ([{ ... }] does not match field "specifiers": [ExportSpecifier] of type ExportNamedDeclaration)

### ISSUE THREAD

**Issue by jkeylu** [facebook/jscodeshift#465]
- foo.ts

```ts
export * as foo from './foo';
```

- transform.js

```js
module.exports = function(fileInfo, api, options) {
  const j = api.jscodeshift;

  return j(fileInfo.source).find(j.ExportNamedDeclaration)
    .forEach(path => {
      if (!path.value.source) {
        return;
      }
      const node = j.exportNamedDeclaration(
        path.value.declaration || null,
        path.value.specifiers,
        j.literal('./bar')
      );
      j(path).replaceWith(node)
    })
    .toSource();
};
```

- command

```sh
jscodeshift --parser=ts -t transform.js foo.ts
```

- output

```
Processing 1 files...
Spawning 1 workers...
Sending 1 files to free worker...
 ERR foo.ts Transformation error ([{ type: ExportNamespaceSpecifier, start: 7, end: 15, loc: [object Object], exported: [object Object] }] does not match field "specifiers": [ExportSpecifier] of type ExportNamedDeclaration)
Error: [{ type: ExportNamespaceSpecifier, start: 7, end: 15, loc: [object Object], exported: [object Object] }] does not match field "specifiers": [ExportSpecifier] of type ExportNamedDeclaration
    at addParam (C:\Users\lsh11409\.bin\node_modules\jscodeshift\node_modules\ast-types\lib\types.js:446:27)
    at C:\Users\lsh11409\.bin\node_modules\jscodeshift\node_modules\ast-types\lib\types.js:469:25
    at Array.forEach (<anonymous>)
    at Function.exportNamedDeclaration (C:\Users\lsh11409\.bin\node_modules\jscodeshift\node_modules\ast-types\lib\types.js:467:35)
    at NodePath.<anonymous> (C:\Users\lsh11409\Desktop\jj\/transform.js:9:22)
    at C:\Users\lsh11409\.bin\node_modules\jscodeshift\src\Collection.js:75:36
    at Array.forEach (<anonymous>)
    at Collection.forEach (C:\Users\lsh11409\.bin\node_modules\jscodeshift\src\Collection.js:74:18)
    at module.exports (C:\Users\lsh11409\Desktop\jj\/transform.js:5:6)
All done. 
Results: 
1 errors
0 unmodified
0 skipped
0 ok
Time elapsed: 1.604seconds
```

**Comment by mobily** [comment]
@jkeylu you may want to use `j.exportAllDeclaration` instead, for instance:

```ts
export default function transformer(file, api) {
  const j = api.jscodeshift;

  return j(file.source).find(j.ExportNamedDeclaration)
    .forEach(path => {
      if (!path.value.source) {
        return;
      }
    
      const { specifiers } = path.value
      
      if (specifiers.length === 1 && specifiers[0].type === 'ExportNamespaceSpecifier') {
        const id = specifiers[0].exported
        const node = j.exportAllDeclaration(
          j.stringLiteral('./bar'),
          id,
        );
        
        j(path).replaceWith(node)
      }
    })
    .toSource();
}

```

AST Explorer: https://astexplorer.net/#/gist/7e568d3539c636c5c880e8eca8c0c651/0904fa6d9556886c3e8110a12e4011b60374b445

**Comment by ElonVolo** [comment]
The question seems to be answered with a vaild workaround.
