### ISSUE TITLE
URL transform doesn't work with TypeScript

### ISSUE THREAD

**Issue by emlai** [facebook/jscodeshift#552]
I have a transform file written in TypeScript. It works when used as a local file (`-t path/to/file`) but not with an URL (`-t https://...`). With an URL transform, jscodeshift fails with the following error:

```
/private/var/folders/sy/sqk95ngs0b7bb6c3872cbvyc0000gn/T/jscodeshift2023222-6764-1d1j47d.za2t.ts?token=GHSAT0AAAAAAAAA6BCXCCVMJWKCSGK3L3UQZA2ZLWQ:8
import type {
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1159:20)
    at Module._compile (node:internal/modules/cjs/loader:1203:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1293:10)
    at Object.newLoader [as .js] (/Users/emlai/.npm/_npx/c5e6d14ea42cfa80/node_modules/pirates/lib/index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:1096:32)
    at Module._load (node:internal/modules/cjs/loader:935:12)
    at Module.require (node:internal/modules/cjs/loader:1120:19)
    at require (node:internal/modules/helpers:112:18)
    at setup (/Users/emlai/.npm/_npx/c5e6d14ea42cfa80/node_modules/jscodeshift/src/Worker.js:91:18)
```

**Comment by Charlygraphy23** [comment]
> SyntaxError: Cannot use import statement outside a module

You must have using import without modules. I think you need to add `"type": "module"` in your package.json file. Or else you can use `require` for importing file

**Comment by mon-jai** [comment]
`mts` doesn't work too.

**Comment by mon-jai** [comment]
@Charlygraphy23 `.mts` doesn't work too.
