### ISSUE TITLE
jscodeshift Using .babelrc project file incorrectly in Babel 6 Environments

### ISSUE THREAD

**Issue by kjanoudi** [facebook/jscodeshift#84]
Scenario: 
* Project using Babel 6, and .babelrc file for project configuration
* Babel 6 installed globally
* jscodeshift is run within the project directory at the same level as the .babelrc file

Result:

```
/usr/local/lib/node_modules/jscodeshift/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126
      if (!option) this.log.error("Unknown option: " + alias + "." + key, ReferenceError);
                           ^

TypeError: Cannot read property 'error' of undefined
    at OptionManager.mergeOptions (/usr/local/lib/node_modules/jscodeshift/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:28)
    at OptionManager.addConfig (/usr/local/lib/node_modules/jscodeshift/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
    at OptionManager.findConfigs (/usr/local/lib/node_modules/jscodeshift/node_modules/babel-core/lib/transformation/file/options/option-manager.js:168:35)
    at OptionManager.init (/usr/local/lib/node_modules/jscodeshift/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
    at compile (/usr/local/lib/node_modules/jscodeshift/node_modules/babel-core/lib/api/register/node.js:117:22)
    at normalLoader (/usr/local/lib/node_modules/jscodeshift/node_modules/babel-core/lib/api/register/node.js:199:14)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/jscodeshift/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
```

Temporary fix:
* Run jscodeshift from outside the project directory, with no .babelrc file in the directory you are running jscodeshift within.

**Comment by kjanoudi** [comment]
This looks like it has to do with https://github.com/facebook/jscodeshift/blob/master/src/Worker.js#L41 

```javascript
function setup(tr, babel) {
  if (babel === 'babel') {
    require('babel-core/register')();
  }
  transform = require(tr);
}
```

With babel 6+, the recommended approach is to use ``require('babel-register')({options})``. 

I think desired behavior would actually be to do this and use the .babelrc file from the project to transform the file correctly? In which case, we would just need to use the babel-register module on environments with babel 6+

**Comment by fkling** [comment]
> I think desired behavior would actually be to do this and use the .babelrc file from the project to transform the file correctly? 

If I understand you correctly, no. You are correct that this is the part that causes the issue, however we use `babel-core/register` only to convert the **transformer** itself, so that one can use ES6 in the transformer. This has nothing to do with the files that should be codemodded.

More generally, jscodeshift shouldn't care what else you are doing with the source files. All it sees is a list of files and it converts those files.

**Comment by kjanoudi** [comment]
@fkling Oh ok, i see what you're saying. In building the project locally and running it, i cannot seem to reproduce the error generated by the globally installed module. I will close the issue until I can

**Comment by fkling** [comment]
Basically we somehow have to prevent that jscodeshift's Babel doesn't pick up any "external" babel configurations. Not sure if that's possible though.

**Comment by kjanoudi** [comment]
@fkling Sending the ``babelrc: false`` option to wherever babel is processing the files would accomplish this, however I'm not certain where that option would be set - or if it's possible to do so without using babel 6
