### ISSUE TITLE
0.3.15: cannot find module 'temp'

### ISSUE THREAD

**Issue by jedwards1211** [facebook/jscodeshift#97]
I just installed 0.3.15 and when I try to run it, I get the following error:

```
Error: Cannot find module 'temp'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/andy/.nvm/versions/node/v5.5.0/lib/node_modules/jscodeshift/dist/Runner.js:27:12)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```

It looks like `temp` is only marked in `devDependencies` in your `package.json`.

Do I misunderstand something or should it be in `dependencies`?

**Comment by jedwards1211** [comment]
I worked around this by doing `npm i -g temp`.
