### ISSUE TITLE
Runner tries to call 'process.std.write' (should that be stdout)?

### ISSUE THREAD

**Issue by jedwards1211** [facebook/jscodeshift#98]
Using 0.3.15:

```
$ jscodeshift -t node_modules/rackt-codemod/transforms/react-router/deprecate-Link-location-props.js app
/Users/andy/.nvm/versions/node/v5.5.0/lib/node_modules/jscodeshift/dist/Runner.js:83
          process.std.write('Skipping path "' + name + '" which does not exist.\n');
                     ^

TypeError: Cannot read property 'write' of undefined
    at /Users/andy/.nvm/versions/node/v5.5.0/lib/node_modules/jscodeshift/dist/Runner.js:83:22
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by fkling** [comment]
Thanks, fixed via 19fe49c69fb29e3eb54a258e121738bc9660eb92. Feel free to send PRs for issues you like this :)

**Comment by jedwards1211** [comment]
ah, cool, I had edited the file but forgot to hit create pull request.  Thanks!

**Comment by jedwards1211** [comment]
That was about the world's fastest breakfix, I'm impressed!
